name: Run Apartment Tracker

on:
  schedule:
    - cron: "0 13 * * *"  # 9 AM EST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 gspread oauth2client

      - name: Run script
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: python tracker.py
